var agents = {
  list: [
    {
      'KIA': false,
      'prison': false,
      'name': 'John',
      'at': 'Russia',
      'rank': 5,
      'experience': 210,
      'originCountry': 'US',
      'operationsSkill': 2,
      'electronicsSkill': 3,
      'stealthSkill': 5,
      'equipmentSlots': 2,
      'equipments': [{'name': ''}, {'name': ''}],
      'ETA': false,
      'ETAtime': null,
      'loyalty': 'normal',
      'MissionsDone': []
    }, {
      'KIA': false,
      'prison': false,
      'name': 'Jeremy',
      'at': 'China',
      'rank': 6,
      'experience': 280,
      'originCountry': 'UK',
      'operationsSkill': 3,
      'electronicsSkill': 5,
      'stealthSkill': 3,
      'equipmentSlots': 3,
      'equipments': [{'name': ''}, {'name': ''}, {'name': ''}],
      'ETA': false,
      'ETAtime': null,
      'loyalty': 'normal',
      'MissionsDone': []
    }, {
      'KIA': false,
      'prison': false,
      'name': 'Joanna',
      'at': 'Russia',
      'rank': 4,
      'experience': 150,
      'originCountry': 'France',
      'operationsSkill': 2,
      'electronicsSkill': 5,
      'stealthSkill': 2,
      'equipmentSlots': 2,
      'equipments': [{'name': ''}, {'name': ''}, {'name': ''}],
      'ETA': false,
      'ETAtime': null,
      'loyalty': 'normal',
      'MissionsDone': []
    }, {
      'KIA': false,
      'prison': false,
      'name': 'Jebediah',
      'at': 'US',
      'rank': 7,
      'experience': 360,
      'originCountry': 'Egypt',
      'operationsSkill': 6,
      'electronicsSkill': 4,
      'stealthSkill': 3,
      'equipmentSlots': 3,
      'equipments': [{'name': ''}, {'name': ''}, {'name': ''}],
      'ETA': false,
      'ETAtime': null,
      'loyalty': 'normal',
      'MissionsDone': []
    }, {
      'KIA': false,
      'prison': false,
      'name': 'Jin',
      'at': 'France',
      'rank': 8,
      'experience': 450,
      'originCountry': 'China',
      'operationsSkill': 8,
      'electronicsSkill': 1,
      'stealthSkill': 4,
      'equipmentSlots': 3,
      'equipments': [{'name': ''}, {'name': ''}, {'name': ''}],
      'ETA': false,
      'ETAtime': null,
      'loyalty': 'normal',
      'MissionsDone': []
    }, {
      'KIA': false,
      'prison': false,
      'name': 'Jesenin',
      'at': 'Russia',
      'rank': 9,
      'experience': 550,
      'originCountry': 'Russia',
      'operationsSkill': 5,
      'electronicsSkill': 3,
      'stealthSkill': 6,
      'equipmentSlots': 3,
      'equipments': [{'name': ''}, {'name': ''}, {'name': ''}],
      'ETA': false,
      'ETAtime': null,
      'loyalty': 'normal',
      'MissionsDone': []
    }, {
      'KIA': false,
      'prison': false,
      'name': 'Julianna',
      'at': 'US',
      'rank': 1,
      'experience': 30,
      'originCountry': 'Scotland',
      'operationsSkill': 3,
      'electronicsSkill': 2,
      'stealthSkill': 2,
      'equipmentSlots': 1,
      'equipments': [{'name': ''}],
      'ETA': false,
      'ETAtime': null,
      'loyalty': 'normal',
      'MissionsDone': []
    }, {
      'KIA': false,
      'prison': false,
      'name': 'Jordy',
      'at': 'MiddleEast',
      'rank': 2,
      'experience': 60,
      'originCountry': 'Sweden',
      'operationsSkill': 1,
      'electronicsSkill': 5,
      'stealthSkill': 2,
      'equipmentSlots': 2,
      'equipments': [{'name': ''}, {'name': ''}],
      'ETA': false,
      'ETAtime': null,
      'loyalty': 'normal',
      'MissionsDone': []
    }, {
	    'KIA': false,
      'prison': false,
      'name': 'Brick',
      'at': 'US',
      'rank': 5,
      'experience': 210,
      'originCountry': 'Norway',
      'operationsSkill': 6,
      'electronicsSkill': 2,
      'stealthSkill': 2,
      'equipmentSlots': 2,
      'equipments': [{'name': ''}, {'name': ''}],
      'ETA': false,
      'ETAtime': null,
      'loyalty': 'normal',
      'MissionsDone': []
	  }
  ]
};

export default agents;
